### ISSUE TITLE
C# Compiler crashing server

### ISSUE THREAD

**Issue by Calytic** [OxideMod/Oxide#464]
I am under the impression that there was an issue when compiling mods that cpu usage spikes and crashes the instance.

My understanding is a fix was pushed recently.  I have since updated to the most recent version of oxide with the fix but am still having compiler related crashes when installing or reloading mods.

**Comment by lukespragg** [comment]
Could you provide the latest compiler and oxide/logs please? The Oxide version you are using would be helpful as wel.

**Comment by Calytic** [comment]
Oxide Version is 2.0.1190
Neither the compiler or oxide logs show any information pertaining to this issue.

**Comment by bawNg** [comment]
Please let us know exactly how long after compiling a plugin you run into this issue.

I discovered an issue 3 days ago which caused the compilers auto-shutdown to freeze servers for an extended period on a small number of machines, this caused the server to lock up exactly 60 seconds after a C# plugin was compiled. I fixed the bug shortly after discovering it, so it should not be possible with recent Oxide builds.

These freezes lasted up to 60 seconds before the server process resumed but did not cause crashes, so if were experiencing this issue, I can only imagine your hosting platform was detecting the frozen server process and killing it.

I am not aware of any other issues related to the compiler, so if you are still experiencing an issue issue, you will need to provide more information so that it can be reproduced.

**Comment by Calytic** [comment]
Basically, I reload ANY plugin, and shortly thereafter (within 30 seconds), the cpu usage spikes above 90%.  My host has high usage restarts, so the server is shut down when usage reaches this point.

**Comment by Calytic** [comment]
The servers CPU usually runs at a cool 15% until compilation and the subsequent crash.  I have tested it with even just one mod enabled and it still happens.  As far as I can tell, the logs provide no information regarding what happens.

**Comment by lukespragg** [comment]
Please provide your latest compiler and Oxide logs for us to review. It doesn't sound like it's the C# compiler causing it, as it happens long after the compiler already finished.

**Comment by Calytic** [comment]
```
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: VendorZone.cs(18,48): warning CS0414: The private field `Oxide.Plugins.VendorZone.Rust' is assigned but its value is never used

[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: 
[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: CycloneUtil.cs(226,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(260,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(283,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(345,71): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CycloneUtil.cs(26,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.requestTimer' is assigned but its value is never used
CycloneUtil.cs(28,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.positionTimer' is assigned but its value is never used
CycloneUtil.cs(30,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.pullTimer' is assigned but its value is never used
CycloneUtil.cs(33,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.raidTimer' is assigned but its value is never used
CycloneUtil.cs(49,16): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.privatemessage' is assigned but its value is never used

[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: SignArtist.cs(348,14): warning CS0114: `Oxide.Plugins.SignArtist.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
SignArtist.cs(289,24): warning CS0219: The variable `name' is assigned but its value is never used

[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: CycloneUtil.cs(226,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(260,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(283,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(345,71): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CycloneUtil.cs(26,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.requestTimer' is assigned but its value is never used
CycloneUtil.cs(28,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.positionTimer' is assigned but its value is never used
CycloneUtil.cs(30,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.pullTimer' is assigned but its value is never used
CycloneUtil.cs(33,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.raidTimer' is assigned but its value is never used
CycloneUtil.cs(49,16): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.privatemessage' is assigned but its value is never used

[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: 
[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: RainOfFire.cs(39,16): warning CS0114: `Oxide.Plugins.RainOfFire.LoadConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
RainOfFire.cs(74,32): warning CS0168: The variable `ex' is declared but never used

[SERVER] Got Message: Exit
[SERVER] Exit received. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: ConstructionConfig.cs(32,14): warning CS0114: `Oxide.Plugins.ConstructionConfig.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ConstructionConfig.cs(136,22): warning CS0114: `Oxide.Plugins.ConstructionConfig.LoadConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)

[SERVER] Connection closed. Shutdown
[SERVER] Started as service
[SERVER] Running as service
[SERVER] Got Message: Ready
[SERVER] Got Message: Compile
[SERVER] Console: AirdropControl.cs(109,14): warning CS0114: `Oxide.Plugins.AirdropControl.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
AntiCheat.cs(589,21): warning CS0108: `Oxide.Plugins.AntiCheat.ForcePlayerPosition(BasePlayer, UnityEngine.Vector3)' hides inherited member `Oxide.Plugins.RustPlugin.ForcePlayerPosition(BasePlayer, UnityEngine.Vector3)'. Use the new keyword if hiding was intended
C:\servers\cyclone\Oxide.Game.Rust.dll (Location of the symbol related to previous warning)
AutoDoorCloser.cs(104,14): warning CS0114: `Oxide.Plugins.AutoDoorCloser.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ConstructionConfig.cs(32,14): warning CS0114: `Oxide.Plugins.ConstructionConfig.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ConstructionConfig.cs(136,22): warning CS0114: `Oxide.Plugins.ConstructionConfig.LoadConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
CycloneStats.cs(39,27): warning CS0108: `Oxide.Plugins.CycloneStats.OccurenceAggregate.type' hides inherited member `Oxide.Plugins.CycloneStats.Occurence.type'. Use the new keyword if hiding was intended
CycloneStats.cs(27,27): (Location of the symbol related to previous warning)
CycloneStats.cs(52,27): warning CS0108: `Oxide.Plugins.CycloneStats.OccurenceSum.type' hides inherited member `Oxide.Plugins.CycloneStats.Occurence.type'. Use the new keyword if hiding was intended
CycloneStats.cs(27,27): (Location of the symbol related to previous warning)
EventManager.cs(155,21): warning CS0108: `Oxide.Plugins.EventManager.ForcePlayerPosition(BasePlayer, UnityEngine.Vector3)' hides inherited member `Oxide.Plugins.RustPlugin.ForcePlayerPosition(BasePlayer, UnityEngine.Vector3)'. Use the new keyword if hiding was intended
C:\servers\cyclone\Oxide.Game.Rust.dll (Location of the symbol related to previous warning)
EventManager.cs(494,14): warning CS0114: `Oxide.Plugins.EventManager.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ItemConfig.cs(41,14): warning CS0114: `Oxide.Plugins.ItemConfig.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ItemConfig.cs(291,22): warning CS0114: `Oxide.Plugins.ItemConfig.LoadConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
Kits.cs(103,14): warning CS0114: `Oxide.Plugins.Kits.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
RainOfFire.cs(39,16): warning CS0114: `Oxide.Plugins.RainOfFire.LoadConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
SignArtist.cs(348,14): warning CS0114: `Oxide.Plugins.SignArtist.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
ZoneManager.cs(53,14): warning CS0114: `Oxide.Plugins.ZoneManager.LoadDefaultConfig()' hides inherited member `Oxide.Core.Plugins.Plugin.LoadDefaultConfig()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
C:\servers\cyclone\Oxide.Core.dll (Location of the symbol related to previous warning)
AdminChat.cs(34,20): warning CS0219: The variable `uid' is assigned but its value is never used
AdminChat.cs(47,29): warning CS0168: The variable `message' is declared but never used
AdminChat.cs(62,24): warning CS0219: The variable `currId' is assigned but its value is never used
AirdropControl.cs(151,17): warning CS0219: The variable `toLeft' is assigned but its value is never used
AirdropControl.cs(242,29): warning CS0168: The variable `startPos' is declared but never used
AirdropControl.cs(243,29): warning CS0168: The variable `endPos' is declared but never used
AirdropControl.cs(244,27): warning CS0168: The variable `distance' is declared but never used
AntiCheat.cs(454,48): warning CS0472: The result of comparing value type `uint' with null is always `true'
AntiCheat.cs(616,62): warning CS0472: The result of comparing value type `UnityEngine.Vector3' with null is always `true'
AntiCheat.cs(1066,24): warning CS0219: The variable `detectionText' is assigned but its value is never used
AntiCheat.cs(1084,24): warning CS0219: The variable `detectionText' is assigned but its value is never used
Clans.cs(660,18): warning CS0168: The variable `otherClan' is declared but never used
Clans.cs(682,34): warning CS0219: The variable `onlineMembers' is assigned but its value is never used
CopyPaste.cs(76,24): warning CS0219: The variable `playerID' is assigned but its value is never used
CopyPaste.cs(242,58): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(252,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(254,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(266,58): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(289,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(291,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(303,58): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(311,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(313,67): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(563,81): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(610,59): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(630,77): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(755,107): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(756,113): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(846,81): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(866,77): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(936,70): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(937,75): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(938,73): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1015,47): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1023,51): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1103,47): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1110,51): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1163,47): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CopyPaste.cs(1169,51): warning CS0618: `UnityEngine.Quaternion.EulerRotation(UnityEngine.Vector3)' is obsolete: `Use Quaternion.Euler instead. This function was deprecated because it uses radians instead of degrees'
CycloneStats.cs(280,25): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(289,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(298,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(315,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(327,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(346,25): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(366,25): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(367,24): warning CS0219: The variable `cause' is assigned but its value is never used
CycloneStats.cs(375,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneStats.cs(388,21): warning CS0219: The variable `pos' is assigned but its value is never used
CycloneUtil.cs(226,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(260,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(283,27): warning CS0219: The variable `rng' is assigned but its value is never used
CycloneUtil.cs(345,71): warning CS0618: `UnityEngine.Quaternion.ToEulerAngles()' is obsolete: `Use Quaternion.eulerAngles instead. This function was deprecated because it uses radians instead of degrees'
EventManager.cs(195,36): warning CS0472: The result of comparing value type `int' with null is always `false'
ExplosivesOwner.cs(111,20): warning CS0219: The variable `hitinfo_name' is assigned but its value is never used
ExplosivesOwner.cs(112,24): warning CS0219: The variable `attacker' is assigned but its value is never used
ExplosivesOwner.cs(113,20): warning CS0219: The variable `attackerID' is assigned but its value is never used
ExplosivesOwner.cs(114,20): warning CS0219: The variable `weapon' is assigned but its value is never used
ExplosivesOwner.cs(158,20): warning CS0219: The variable `weapon' is assigned but its value is never used
RainOfFire.cs(74,32): warning CS0168: The variable `ex' is declared but never used
RemoverTool.cs(375,33): warning CS0162: Unreachable code detected
SignArtist.cs(289,24): warning CS0219: The variable `name' is assigned but its value is never used
Skills.cs(932,30): warning CS0219: The variable `profile' is assigned but its value is never used
Skills.cs(1203,20): warning CS0219: The variable `furnaceType' is assigned but its value is never used
Skills.cs(1372,35): warning CS0219: The variable `armoreffective' is assigned but its value is never used
Skills.cs(1442,34): warning CS0219: The variable `profile' is assigned but its value is never used
Skills.cs(1490,20): warning CS0219: The variable `playerID' is assigned but its value is never used
Skills.cs(1491,26): warning CS0219: The variable `profile' is assigned but its value is never used
Skills.cs(1494,41): warning CS0219: The variable `salvaged' is assigned but its value is never used
Skills.cs(1514,20): warning CS0219: The variable `playerID' is assigned but its value is never used
Skills.cs(1515,26): warning CS0219: The variable `profile' is assigned but its value is never used
Skills.cs(1763,34): warning CS0472: The result of comparing value type `BuildingGrade.Enum' with null is always `false'
Skills.cs(1819,97): warning CS0472: The result of comparing value type `BuildingGrade.Enum' with null is always `true'
Skills.cs(2131,19): warning CS0219: The variable `condition' is assigned but its value is never used
Skills.cs(2563,20): warning CS0219: The variable `playerID' is assigned but its value is never used
Skills.cs(2630,20): warning CS0219: The variable `playerID' is assigned but its value is never used
Skills.cs(2758,19): warning CS0219: The variable `skillDiff' is assigned but its value is never used
ZoneManager.cs(586,29): warning CS0184: The given expression is never of the provided (`WorldItem') type
ZoneManager.cs(588,17): warning CS0162: Unreachable code detected
AirdropControl.cs(19,27): warning CS0414: The private field `Oxide.Plugins.AirdropControl.CPsecondsTaken' is assigned but its value is never used
AirdropControl.cs(21,28): warning CS0169: The private field `Oxide.Plugins.AirdropControl.CreateEntity' is never used
AirdropControl.cs(23,23): warning CS0169: The private field `Oxide.Plugins.AirdropControl.secondsToTake' is never used
AirdropControl.cs(24,28): warning CS0169: The private field `Oxide.Plugins.AirdropControl.cargoplane' is never used
AirdropControl.cs(25,49): warning CS0414: The private field `Oxide.Plugins.AirdropControl.dropPoint' is assigned but its value is never used
AirdropControl.cs(42,24): warning CS0414: The private field `Oxide.Plugins.AirdropControl.syncLock' is assigned but its value is never used
AntiCheat.cs(50,20): warning CS0414: The private field `Oxide.Plugins.AntiCheat.constructionColl' is assigned but its value is never used
AntiCheat.cs(51,20): warning CS0649: Field `Oxide.Plugins.AntiCheat.bulletmask' is never assigned to, and will always have its default value `0'
AntiCheat.cs(76,22): warning CS0414: The private field `Oxide.Plugins.AntiCheat.resetTime' is assigned but its value is never used
AntiCheat.cs(957,28): warning CS0649: Field `Oxide.Plugins.AntiCheat.PlayerLog.lastPosition' is never assigned to, and will always have its default value
Build.cs(114,28): warning CS0169: The private field `Oxide.Plugins.Build.CreateEntity' is never used
Build.cs(115,28): warning CS0169: The private field `Oxide.Plugins.Build.FindPrefab' is never used
Build.cs(148,38): warning CS0169: The private field `Oxide.Plugins.Build.buildingblock' is never used
Build.cs(442,27): warning CS0414: The private field `Oxide.Plugins.Build.socks' is assigned but its value is never used
CopyPaste.cs(147,24): warning CS0169: The private field `Oxide.Plugins.CopyPaste.cleanDeployedName' is never used
CycloneStats.cs(185,44): warning CS0414: The private field `Oxide.Plugins.CycloneStats.Animals' is assigned but its value is never used
CycloneUtil.cs(26,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.requestTimer' is assigned but its value is never used
CycloneUtil.cs(28,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.positionTimer' is assigned but its value is never used
CycloneUtil.cs(30,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.pullTimer' is assigned but its value is never used
CycloneUtil.cs(33,23): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.raidTimer' is assigned but its value is never used
CycloneUtil.cs(49,16): warning CS0414: The private field `Oxide.Plugins.CycloneUtil.privatemessage' is assigned but its value is never used
EventManager.cs(34,24): warning CS0169: The private field `Oxide.Plugins.EventManager.itemname' is never used
EventManager.cs(40,22): warning CS0169: The private field `Oxide.Plugins.EventManager.isBP' is never used
EventManager.cs(41,22): warning CS0414: The private field `Oxide.Plugins.EventManager.Changed' is assigned but its value is never used
EventManager.cs(46,32): warning CS0169: The private field `Oxide.Plugins.EventManager.itemdefinition' is never used
EventManager.cs(48,21): warning CS0169: The private field `Oxide.Plugins.EventManager.stackable' is never used
EventManager.cs(49,21): warning CS0169: The private field `Oxide.Plugins.EventManager.giveamount' is never used
ExplosivesModifier.cs(48,16): warning CS0414: The private field `Oxide.Plugins.ExplosivesModifier.defaultHelpTextPlayerRockets' is assigned but its value is never used
ExplosivesModifier.cs(71,16): warning CS0649: Field `Oxide.Plugins.ExplosivesModifier.helpTextPlayerRockets' is never assigned to, and will always have its default value `null'
ExplosivesModifier.cs(77,16): warning CS0169: The private field `Oxide.Plugins.ExplosivesModifier.modified' is never used
ExplosivesOwner.cs(27,16): warning CS0169: The private field `Oxide.Plugins.ExplosivesOwner.BuildingOwners' is never used
Kits.cs(30,22): warning CS0169: The private field `Oxide.Plugins.Kits.Changed' is never used
RemoverTool.cs(27,22): warning CS0414: The private field `Oxide.Plugins.RemoverTool.useToolCupboard' is assigned but its value is never used
RemoverTool.cs(28,22): warning CS0169: The private field `Oxide.Plugins.RemoverTool.useRustIO' is never used
RemoverTool.cs(33,24): warning CS0169: The private field `Oxide.Plugins.RemoverTool.noFriend' is never used
RemoverTool.cs(50,28): warning CS0169: The private field `Oxide.Plugins.RemoverTool.isInstalled' is never used
RemoverTool.cs(51,28): warning CS0169: The private field `Oxide.Plugins.RemoverTool.hasFriend' is never used
Skills.cs(686,36): warning CS0414: The private field `Oxide.Plugins.Skills.Messages' is assigned but its value is never used
Skills.cs(697,54): warning CS0169: The private field `Oxide.Plugins.Skills.Data' is never used
Skills.cs(698,48): warning CS0414: The private field `Oxide.Plugins.Skills.Rust' is assigned but its value is never used
VendorZone.cs(18,48): warning CS0414: The private field `Oxide.Plugins.VendorZone.Rust' is assigned but its value is never used
ZoneManager.cs(176,19): warning CS0414: The private field `Oxide.Plugins.ZoneManager.Zone.radiationamount' is assigned but its value is never used
ZoneManager.cs(333,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.name' is never assigned to, and will always have its default value `null'
ZoneManager.cs(337,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.autolights' is never assigned to, and will always have its default value `null'
ZoneManager.cs(338,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.eject' is never assigned to, and will always have its default value `null'
ZoneManager.cs(339,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.pvpgod' is never assigned to, and will always have its default value `null'
ZoneManager.cs(340,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.pvegod' is never assigned to, and will always have its default value `null'
ZoneManager.cs(341,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.sleepgod' is never assigned to, and will always have its default value `null'
ZoneManager.cs(342,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.undestr' is never assigned to, and will always have its default value `null'
ZoneManager.cs(343,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nobuild' is never assigned to, and will always have its default value `null'
ZoneManager.cs(344,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.notp' is never assigned to, and will always have its default value `null'
ZoneManager.cs(345,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nochat' is never assigned to, and will always have its default value `null'
ZoneManager.cs(346,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nogather' is never assigned to, and will always have its default value `null'
ZoneManager.cs(347,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nopve' is never assigned to, and will always have its default value `null'
ZoneManager.cs(348,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nowounded' is never assigned to, and will always have its default value `null'
ZoneManager.cs(349,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nodecay' is never assigned to, and will always have its default value `null'
ZoneManager.cs(350,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nodeploy' is never assigned to, and will always have its default value `null'
ZoneManager.cs(351,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nokits' is never assigned to, and will always have its default value `null'
ZoneManager.cs(352,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.noboxloot' is never assigned to, and will always have its default value `null'
ZoneManager.cs(353,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.noplayerloot' is never assigned to, and will always have its default value `null'
ZoneManager.cs(354,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nocorpse' is never assigned to, and will always have its default value `null'
ZoneManager.cs(355,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.nosuicide' is never assigned to, and will always have its default value `null'
ZoneManager.cs(356,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.killsleepers' is never assigned to, and will always have its default value `null'
ZoneManager.cs(357,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.radiation' is never assigned to, and will always have its default value `null'
ZoneManager.cs(358,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.enter_message' is never assigned to, and will always have its default value `null'
ZoneManager.cs(359,27): warning CS0649: Field `Oxide.Plugins.ZoneManager.ZoneDefinition.leave_message' is never assigned to, and will always have its default value `null'
```

It just happened again.  It appears to be intermittent.  Reloaded several mods without issue, then at the 6th or 7th time - crash.

There doesnt appear to be any particular mod causing this, will happen with any mod.  Server crashed within 2 seconds of reload this time.

**Comment by Calytic** [comment]
This one is weird.  So I tested this on a different provider and could not trigger a crash.  I contacted my providers support and they suspect it is actually an error in their monitoring software "detecting" high cpu usage and restarting the server.  According to their monitoring software, when I run the oxide compiler, my server is apparently using 50 out of 32 cores which is obviously impossible.

**Comment by Calytic** [comment]
My apologies for creating this issue.  The effects of this problem were so similar to the compiler crashes due to improper shutdown that I assumed that it must be the case.

**Comment by lukespragg** [comment]
No worries. :)
